name: Workflow qui se déclenche lors de la création d'une issue
on:
  issues:
    types:
      - opened

jobs:
  commentaire:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment $ISSUE_URL --body "Merci d'avoir ouvert cette issue !"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
  output:
    runs-on: ubuntu-latest
    steps:
      - name: sans variable d'environnement
        run: echo Nouvelle issue - ${{ github.event.issue.title }}
      - name: avec variable d'environnement
        env:
          TITRE: ${{ github.event.issue.title }}
        run: |
          echo Nouvelle issue - "$TITRE"
          echo "L'utilisation d'une variable d'environnement intermédiaire atténue le risque d'injection de code"